services:
  mangas:
    build: .
    image: mangas
    container_name: mangas
    command: npm run dev
    volumes:
      - .:/app
    env_file:
      - .env.development
    environment:
      - runDocker=true
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - 9229:9229
      - 3001:3001
    networks:
      - mangas

networks:
  mangas:
    external: true
