services:
  mangas:
    build: .
    image: mangas
    container_name: mangas
    command: npm run dev
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 9229:9229
      - 3001:3001
