---
networks:
  cache:
    external: true
  proxy:
    external: true
  database:
    external: true

services:
  mangas:
    image: pedroh1510/mangas
    container_name: mangas
    restart: unless-stopped
    networks:
      - cache
      - proxy
      - database
    volumes:
      - ${STORAGE}/mangas:/app/downloads
      - ${DATA}/mangas/appdata:/app/appdata
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
      - TZ=${TZ}
    ports:
      - ${PORT}:${PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.mangas-rss.rule=Host(`mangas.${DOMAIN}`)
      - traefik.http.routers.mangas-rss.entrypoints=websecure
      - traefik.http.routers.mangas-rss.tls=true
      - traefik.http.services.mangas-rss.loadbalancer.server.port=${PORT}
      - traefik.docker.network=proxy
  kavita:
    image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
    container_name: kavita
    volumes:
        - ${STORAGE}/mangas:/manga            # Manga is just an example you can have the name you want. See the following
        # - ./comics:/comics          # Use as many as you want
        # - ./books:/books            #
        - ${DATA}/kavita:/kavita/config     # Change './data if you want to have the config files in a different place.
                                    # /kavita/config must not be changed
    environment:
      - TZ=${TZ}
    ports:
      - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`kavita.${DOMAIN}`)
      - traefik.http.routers.kavita.entrypoints=websecure
      - traefik.http.routers.kavita.tls=true
      - traefik.http.services.kavita.loadbalancer.server.port=5000
      - traefik.docker.network=proxy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1000m'
        reservations:
          # cpus: '0.5'
          memory: '500m'  
