name: services-dev
services:
  database:
    image: postgres:16-alpine
    container_name: database-dev-mangas
    restart: unless-stopped
    ports:
      - 15432:5432
    env_file:
      - ../../.env.development
    networks:
      - mangas
  cache:
    image: redis:7-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - mangas

networks:
  mangas:
    external: true