import { config } from 'dotenv';
config();

const CONFIG_ENV = {};
export default CONFIG_ENV;

CONFIG_ENV.ENV = process.env.ENV ?? process.env.NODE_ENV;

CONFIG_ENV.DATABASE_URL = process.env.DATABASE_URL;
CONFIG_ENV.POSTGRES_HOST = process.env.POSTGRES_HOST;
CONFIG_ENV.POSTGRES_PORT = process.env.POSTGRES_PORT;
CONFIG_ENV.POSTGRES_DB = process.env.POSTGRES_DB;
CONFIG_ENV.POSTGRES_USER = process.env.POSTGRES_USER;
CONFIG_ENV.POSTGRES_PASSWORD = process.env.POSTGRES_PASSWORD;
CONFIG_ENV.APPLICATION_NAME = process.env.APPLICATION_NAME;
